<a href="https://colab.research.google.com/github/sourovw/Mathematics/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [14]:
# dataset

D = array([[1, 0], [8, 0], [1, 4]])
print(D)

[[1 0]
 [8 0]
 [1 4]]


In [15]:
print(D.T)

[[1 8 1]
 [0 0 4]]


In [16]:
# calculating mean

M = mean(D.T, axis = 1)
print(M)

[3.33333333 1.33333333]


In [17]:
A = D - M
print(A)

[[-2.33333333 -1.33333333]
 [ 4.66666667 -1.33333333]
 [-2.33333333  2.66666667]]


In [18]:
# claculating covariance matrix

C = cov(A.T)
print(C)

[[16.33333333 -4.66666667]
 [-4.66666667  5.33333333]]


In [19]:
eig_values, eig_vectors = eig(C)

In [20]:
# print eigen values

print(eig_values)

[18.04636167  3.620305  ]


In [21]:
# print eigen vectors

print(eig_vectors)

[[ 0.9387516   0.34459459]
 [-0.34459459  0.9387516 ]]


In [22]:
pca = eig_vectors.T.dot(A.T)

In [23]:
# print principle component

print(pca)

[[-1.73096095  4.84030026 -3.10933931]
 [-2.05572285  0.35643929  1.69928356]]
